apiVersion: v1
kind: Service
metadata:
  name: hlx-html2pdf
  labels:
    app: hlx-html2pdf
spec:
  selector:
    app: hlx-html2pdf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
