apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlx-html2pdf
  labels:
    app: hlx-html2pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlx-html2pdf
  template:
    metadata:
      labels:
        app: hlx-html2pdf
    spec:
      containers:
        - name: html2pdf
          image: your-registry/hlx-html2pdf:latest  # <-- change to your image
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
